if(NOT DEFINED OUT OR OUT STREQUAL "")
  message(FATAL_ERROR "OUT is required")
endif()
if(NOT DEFINED INPUT_DIR OR INPUT_DIR STREQUAL "")
  message(FATAL_ERROR "INPUT_DIR is required")
endif()
if(NOT DEFINED INPUTS OR INPUTS STREQUAL "")
  message(FATAL_ERROR "INPUTS is required")
endif()

get_filename_component(out_dir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")
string(REPLACE "|" ";" js_files "${INPUTS}")

file(WRITE "${OUT}" "package com.ejs.modules.path;\n\nfinal class EJSPathBundle {\n    static final Script[] SCRIPTS = new Script[] {\n")
foreach(js_file IN LISTS js_files)
  file(READ "${INPUT_DIR}/${js_file}" source)
  string(REPLACE "\\" "\\\\" source "${source}")
  string(REPLACE "\"" "\\\"" source "${source}")
  string(REPLACE "\r" "\\r" source "${source}")
  string(REPLACE "\t" "\\t" source "${source}")
  string(REPLACE "\n" "\\n\"\n        + \"" source "${source}")
  file(APPEND "${OUT}" "        new Script(\"${js_file}\", \"${source}\"),\n")
endforeach()
file(APPEND "${OUT}" "    };\n\n    private EJSPathBundle() {}\n\n    static final class Script {\n        final String name;\n        final String source;\n\n        Script(String name, String source) {\n            this.name = name;\n            this.source = source;\n        }\n    }\n}\n")
